### ISSUE TITLE
How to build libcrfsuite.so in Linux env?

### ISSUE THREAD

**Issue by lyc1116** [vinhkhuc/jcrfsuite#10]
Hi vinhkhuc,

I have modified the original crfsuite and want to build the libcrfsuite.so in linux. As https://dl.dropboxusercontent.com/u/11628772/crfsuite-linux-build.tar.gz listed in ISSUE#6 is no longer accessible. Could you help provide the steps of building the so file again?

**Comment by vinhkhuc** [comment]
Hi lyc1116,
You can get the file crfsuite-linux-build.tar.gz at https://github.com/vinhkhuc/jcrfsuite/tree/master/misc.

Thanks,
Vinh

**Comment by lyc1116** [comment]
Thank you very much, a big help!
