### ISSUE TITLE
Unable to use in Linux environment

### ISSUE THREAD

**Issue by pushpit** [vinhkhuc/jcrfsuite#6]
I am not able to use the jar in linux environment. Getting following error:

java.lang.UnsatisfiedLinkError: /tmp/crfsuite-0.12-libcrfsuite.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/crfsuite-0.12-libcrfsuite.so)

Can you please provide me the steps to compile the native library again for my linux environment?

**Comment by vinhkhuc** [comment]
Hi pushpit,
You can download the linux build from https://dl.dropboxusercontent.com/u/11628772/crfsuite-linux-build.tar.gz

After decompressing, you can run the script build.sh to generate libcrfsuite.so. Then replace the old one in src/main/resources/crfsuite-0.12/Linux/ with it.

**Comment by vinhkhuc** [comment]
@pushpit Hi again pushpit, have you successfully compiled the native library?

**Comment by vinhkhuc** [comment]
I assume that the issue was resolved. Feel free to reopen it.

**Comment by devavratrk** [comment]
@vinhkhuc : I am facing the same issue while running on Linux. Unfortunately, your Dropbox link does not work anymore. Any solutions?
