### ISSUE TITLE
How to Use Bigram feature in Jcrfsuite

### ISSUE THREAD

**Issue by shabir1** [vinhkhuc/jcrfsuite#8]
how to Use Bigram feature in Jcrfsuite.
in CRF++ we write B in template file, how we use that feature in jcrfsuite

**Comment by vinhkhuc** [comment]
Hi shabir1,
Unfortunately, crfsuite doesn't support bigram features as in CRF++. For more details: https://github.com/scrapinghub/python-crfsuite/issues/41.
