### ISSUE TITLE
How to prepare training data for NER？

### ISSUE THREAD

**Issue by ibisheng** [vinhkhuc/jcrfsuite#9]
Hi vinhkhuc, I want to use jcrfsuite for  Chinese Named Entity Recognition ( NER)，and I don't know how to prepare the training data, I hope you can give me a hand. Thank you very much！

**Comment by vinhkhuc** [comment]
Hi ibisheng,
Jcrfsuite is fully compatible with crfsuite. You can take a look at how the data is prepared at http://www.chokkan.org/software/crfsuite/tutorial.html.

Thanks,
Vinh

**Comment by ibisheng** [comment]
Thanks for your answer，I finished this issue yesterday. Thanks again!
